### ISSUE TITLE
sparkitecture - Logistic Regression

### ISSUE THREAD

**Issue by jessie-jiang-jiang** [colbyford/sparkitecture#2]
Under 'Define how you want the model to be evaluated',
metricName should be areaUnder**ROC**

<img width="591" alt="lr_metric" src="https://user-images.githubusercontent.com/48604951/68316024-bb869b00-0086-11ea-8d1f-9e95fd4230f3.PNG">

**Comment by colbyford** [comment]
Thanks for catching this typo. I've fixed the AUC to ROC.
